// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlqCYN_cvipQNQ0fvWqiNrEiZaXZHmXps',
    appId: '1:394154337369:android:39067f05fa6ea9412c7d48',
    messagingSenderId: '394154337369',
    projectId: 'taka-wallet-app',
    storageBucket: 'taka-wallet-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwOxQKGOxGM0ckCsAax4y52EG5JraP89s',
    appId: '1:394154337369:ios:0ca24458c11d8c772c7d48',
    messagingSenderId: '394154337369',
    projectId: 'taka-wallet-app',
    storageBucket: 'taka-wallet-app.firebasestorage.app',
    androidClientId: '394154337369-meha2bvhuov0p4pse5085cb1m39aocqt.apps.googleusercontent.com',
    iosClientId: '394154337369-rm777tt3ns9m6fp4hojqqqtdlcdkj8d0.apps.googleusercontent.com',
    iosBundleId: 'com.example.takaAdmin',
  );
}
